import { useEffect, useState } from 'react';
import { ArrowRight, MapPin, Users, Clock, Sparkles } from 'lucide-react';
import type { Profile } from '../../../../../packages/shared/src/profile';
import type { MatchGroup, Participant } from '../../../../../packages/shared/src/matching';
export default function MatchingPage({ profile, onEdit, onJoin }: { profile: Profile; onEdit: () => void; onJoin: (group: MatchGroup) => void }) {
 const [waiting, setWaiting] = useState(false);
 const [count, setCount] = useState(1);
 useEffect(() => { if (!waiting || count === 4) return; const timer = window.setTimeout(() => setCount(c => c + 1), 2200); return () => window.clearTimeout(timer); }, [waiting, count]);
 const participants: Participant[] = [{ id: profile.id, name: profile.name, interests: profile.interests }, ...['Alex', 'Jordan', 'Sam'].map((name, i) => ({ id: `demo-${i}`, name, interests: profile.interests.slice(0, 2) }))];
 return <section className="page-content"><div className="eyebrow">YOUR PEOPLE ARE OUT THERE</div><h1>A good conversation<br/>starts with <em>hello.</em></h1><p className="muted">Four people, shared interests, and a little room for the unexpected.</p><div className="queue-layout"><div className="surface queue-main"><div className="section-top"><span className="pill"><span className="status-dot"/> Demo matching</span><span className="muted"><MapPin size={14}/> {profile.location} · {profile.radiusKm} km</span></div><h2>{count === 4 ? 'Your group is ready.' : waiting ? 'Making room for your people…' : 'Meet your next conversation.'}</h2><p className="muted">{count === 4 ? 'Everyone’s here. Take a breath and say hello.' : 'A small group. A shared spark. No crowded rooms.'}</p><div className="queue-people">{participants.map((p, i) => <div key={p.id}><div className={`queue-avatar ${i < count ? `filled color-${i}` : ''}`}>{i < count ? p.name.slice(0, 1).toUpperCase() : <Users size={23}/>}</div><strong>{i === 0 ? 'You' : i < count ? p.name : 'Someone new'}</strong><small>{i === 0 ? 'Ready to connect' : i < count ? 'Demo participant' : 'An open seat'}</small></div>)}</div><div className="queue-message" role="status" aria-live="polite">{waiting ? `${count} of 4 people · ${count === 4 ? 'Ready when you are' : 'Finding shared interests'}` : 'Your seat is waiting.'}</div>{count === 4 ? <button className="primary" onClick={() => onJoin({ id: 'demo-group', roomId: 'demo-room', participants })}>Enter demo room<ArrowRight size={18}/></button> : <button className="primary" disabled={waiting} onClick={() => setWaiting(true)}>{waiting ? 'Finding your group…' : 'Join the queue'}<ArrowRight size={18}/></button>}{waiting && <button className="text-button" onClick={() => { setWaiting(false); setCount(1); }}>Leave queue</button>}<p className="field-hint">Simulated matches with three seeded participants. Live availability is not connected.</p></div><aside className="queue-sidebar"><div className="surface"><div className="section-top"><h3>Your common ground</h3><button className="text-button" onClick={onEdit}>Edit</button></div><div className="interest-list">{profile.interests.map(i => <span className="interest selected" key={i}>{i}</span>)}</div><p className="field-hint">Matching will use your interests and approximate location.</p></div><div className="surface what-next"><h3>A little of what to expect</h3><p><Users size={19}/><span><strong>Just four of you</strong>A conversation everyone has space in.</span></p><p><Sparkles size={19}/><span><strong>Skip the awkward start</strong>Prompts inspired by what you love.</span></p><p><Clock size={19}/><span><strong>20 minutes to connect</strong>Then discover local things to do together.</span></p></div></aside></div></section>;
}
